version: '3.8'

services:
  speedtest:
    build: .
    expose:
      - "8050"
    volumes:
      - ./speedtest_results.json:/app/speedtest_results.json
      - ./.env:/app/.env
    environment:
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - speedtest 